In [1]:
import pandas as pd
from datetime import timedelta

# Read the CSV file
data_15 = pd.read_csv('travel_times_15_17.csv')

# Convert departure_time to datetime
data_15['departure_time'] = pd.to_datetime(data_15['departure_time'])

data_15 = data_15[data_15['departure_time'] != '2025-12-18 17:00:00']
# Create an empty list to store the new rows
new_rows = []

# For each unique timestamp in the original data
unique_times = sorted(data_15['departure_time'].unique())

for time in unique_times:
    # Get all rows for this timestamp
    rows_at_time = data_15[data_15['departure_time'] == time]
    
    # Add the original rows
    new_rows.append(rows_at_time)
    
    # Create duplicate rows with +10 minutes
    rows_plus_10 = rows_at_time.copy()
    rows_plus_10['departure_time'] = time + timedelta(minutes=10)
    new_rows.append(rows_plus_10)

# Concatenate all rows
result_df_15 = pd.concat(new_rows, ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
result_df_15 = result_df_15.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)

# Save to new CSV file
result_df_15.to_csv('interpolated_data.csv', index=False)

print(f"Original data shape: {data_15.shape}")
print(f"New data shape: {result_df_15.shape}")
print(f"\nFirst few rows:")
print(result_df_15.head(20))

Original data shape: (2772, 15)
New data shape: (5544, 15)

First few rows:
        departure_time  origin_station_id         origin_name  origin_lat  \
0  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
1  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
2  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
3  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
4  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
5  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
6  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
7  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
8  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
9  2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   
10 2025-12-18 15:00:00            8504622  Fribourg, Bellevue   46.810927   


In [2]:
import pandas as pd
from datetime import timedelta

# Read the CSV file
data_19 = pd.read_csv('travel_times_19_21.csv')

# Convert departure_time to datetime
data_19['departure_time'] = pd.to_datetime(data_19['departure_time'])


# Create an empty list to store the new rows
new_rows = []

# For each unique timestamp in the original data
unique_times = sorted(data_19['departure_time'].unique())

for time in unique_times:
    # Get all rows for this timestamp
    rows_at_time = data_19[data_19['departure_time'] == time]
    
    # Add the original rows
    new_rows.append(rows_at_time)
    
    # Create duplicate rows with +10 minutes
    rows_plus_10 = rows_at_time.copy()
    rows_plus_10['departure_time'] = time + timedelta(minutes=10)
    new_rows.append(rows_plus_10)

# Concatenate all rows
result_df_19 = pd.concat(new_rows, ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
result_df_19 = result_df_19.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)


result_df_19 = result_df_19[result_df_19['departure_time'] != '2025-12-18 21:10:00']

# Save to new CSV file
result_df_19.to_csv('interpolated_data.csv', index=False)
print(f"Original data shape: {data_19.shape}")
print(f"New data shape: {result_df_19.shape}")
print(f"\nFirst few rows:")
print(result_df_19.head(20))

Original data shape: (3234, 15)
New data shape: (6006, 15)

First few rows:
        departure_time  origin_station_id         origin_name  origin_lat  \
0  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
1  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
2  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
3  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
4  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
5  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
6  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
7  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
8  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
9  2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   
10 2025-12-18 19:00:00            8504622  Fribourg, Bellevue   46.810927   


In [3]:
data_17 = pd.read_csv('travel_times_17_19.csv')
data_17['departure_time'] = pd.to_datetime(data_17['departure_time'])
result_df_17 = data_17[data_17['departure_time'] != '2025-12-18 19:00:00']
result_df_17.to_csv('interpolated_data.csv', index=False)

In [4]:
# Concatenate the three dataframes vertically
combined_df = pd.concat([result_df_15, result_df_17, result_df_19], ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
combined_df = combined_df.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)

# Save to new CSV file
combined_df.to_csv('combined_data.csv', index=False)

In [5]:
combined_df

departure_time  origin_station_id                     origin_name  \
0     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
1     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
2     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
3     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
4     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
...                   ...                ...                             ...   
17089 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17090 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17091 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17092 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17093 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   

       origin_lat  origin_lon  dest_station_id                     dest_name  \
0       46.810927    7.171933          8589141              Fribourg, Chaley   
1       46.810927    7.171933          8589152           Fribourg, Mon-Repos   
2       46.810927    7.171933          8589138        Fribourg, Cité-Jardins   
3       46.810927    7.171933          8591766            Fribourg, Boschung   
4       46.810927    7.171933          8587255  Fribourg, Tilleul/Cathédrale   
...           ...         ...              ...                           ...   
17089   46.803875    7.137564          8591767      Fribourg, Route-de-Tavel   
17090   46.803875    7.137564          8589270             Fribourg, Kessler   
17091   46.803875    7.137564          8589147           Fribourg, Ploetscha   
17092   46.803875    7.137564          8589158              Fribourg, Windig   
17093   46.803875    7.137564          8587356     Fribourg, Pont-Zaehringen   

        dest_lat  dest_lon  distance_meters  duration_seconds  \
0      46.805855  7.175769              891               117   
1      46.806576  7.172542              624                84   
2      46.809219  7.170362              223                31   
3      46.811443  7.171201              134                21   
4      46.806136  7.161448             2907               334   
...          ...       ...              ...               ...   
17089  46.810716  7.176105             5223               738   
17090  46.812164  7.173227             5065               724   
17091  46.813063  7.173218             5165               734   
17092  46.816509  7.173966             5556               768   
17093  46.806498  7.166630             5831               814   

       duration_minutes  duration_in_traffic_seconds  \
0                  1.95                          134   
1                  1.40                          101   
2                  0.52                           37   
3                  0.35                           26   
4                  5.57                          361   
...                 ...                          ...   
17089             12.30                          645   
17090             12.07                          625   
17091             12.23                          635   
17092             12.80                          668   
17093             13.57                          692   

       duration_in_traffic_minutes status  
0                             2.23     OK  
1                             1.68     OK  
2                             0.62     OK  
3                             0.43     OK  
4                             6.02     OK  
...                            ...    ...  
17089                        10.75     OK  
17090                        10.42     OK  
17091                        10.58     OK  
17092                        11.13     OK  
17093                        11.53     OK  

[17094 rows x 15 columns]

In [6]:
print(combined_df)

           departure_time  origin_station_id                     origin_name  \
0     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
1     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
2     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
3     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
4     2025-12-18 15:00:00            8504622              Fribourg, Bellevue   
...                   ...                ...                             ...   
17089 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17090 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17091 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17092 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   
17093 2025-12-18 21:00:00            8592378  Villars-sur-Glâne,Jean Paul II   

       origin_lat  origin_lon  dest_sta

In [7]:
import numpy as np
data = np.load('data/travel_time_all_zero.npy')
data

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [8]:
import pandas as pd
import numpy as np
import json

# Read the JSON file with station information
with open('data/stations.json', 'r', encoding='utf-8') as f:
    stations_data = json.load(f)

# Create a mapping from station_id to index
station_id_to_index = {station['station_id']: station['index'] 
                       for station in stations_data['stations']}

# Convert departure_time to datetime if not already
combined_df['departure_time'] = pd.to_datetime(combined_df['departure_time'])

# Get unique timestamps and sort them
unique_times = sorted(combined_df['departure_time'].unique())
print(f"Number of unique timestamps: {len(unique_times)}")
print(f"Time range: {unique_times[0]} to {unique_times[-1]}")

# Filter to only keep times from 15:00 to 21:00 (36 slots: every 10 minutes)
start_time = pd.to_datetime('2025-12-18 15:00:00')
end_time = pd.to_datetime('2025-12-18 21:00:00')

filtered_times = [t for t in unique_times if start_time <= t < end_time]
print(f"\nFiltered timestamps: {len(filtered_times)}")
print(f"First few: {filtered_times[:5]}")
print(f"Last few: {filtered_times[-5:]}")

# Check if we have exactly 36 time slots
if len(filtered_times) != 36:
    print(f"\nWARNING: Expected 36 time slots but got {len(filtered_times)}")
    print("Adjusting matrix size...")

# Initialize the 3D array with actual number of time slots
n_time_slots = len(filtered_times)
travel_time_matrix = np.zeros((22, 22, n_time_slots), dtype=np.float32)

# Fill the matrix with travel times
for time_idx, timestamp in enumerate(filtered_times):
    # Get all rows for this timestamp
    time_slice = combined_df[combined_df['departure_time'] == timestamp]
    
    for _, row in time_slice.iterrows():
        origin_id = str(row['origin_station_id'])
        dest_id = str(row['dest_station_id'])
        
        # Check if both stations are in our station mapping
        if origin_id in station_id_to_index and dest_id in station_id_to_index:
            origin_idx = station_id_to_index[origin_id]
            dest_idx = station_id_to_index[dest_id]
            
            # Use duration_in_traffic_minutes as the travel time
            travel_time = row['duration_in_traffic_minutes'] * 60
            
            # Store in the matrix
            travel_time_matrix[origin_idx, dest_idx, time_idx] = travel_time

# Save the numpy array
np.save('data/travel_time_matrix.npy', travel_time_matrix)

print(f"\n=== FINAL RESULTS ===")
print(f"Matrix shape: {travel_time_matrix.shape}")
print(f"Matrix dtype: {travel_time_matrix.dtype}")
print(f"\nSample values at time slot 0 (15:00):")
print(travel_time_matrix[:5, :5, 0])
print(f"\nNon-zero entries: {np.count_nonzero(travel_time_matrix)}")
print(f"Total entries: {travel_time_matrix.size}")
print(f"Percentage filled: {100 * np.count_nonzero(travel_time_matrix) / travel_time_matrix.size:.2f}%")

# Verify: check a specific route
print("\nVerification - Travel time from station 0 to station 1 across all time slots:")
print(travel_time_matrix[0, 1, :])

Number of unique timestamps: 37
Time range: 2025-12-18 15:00:00 to 2025-12-18 21:00:00

Filtered timestamps: 36
First few: [Timestamp('2025-12-18 15:00:00'), Timestamp('2025-12-18 15:10:00'), Timestamp('2025-12-18 15:20:00'), Timestamp('2025-12-18 15:30:00'), Timestamp('2025-12-18 15:40:00')]
Last few: [Timestamp('2025-12-18 20:10:00'), Timestamp('2025-12-18 20:20:00'), Timestamp('2025-12-18 20:30:00'), Timestamp('2025-12-18 20:40:00'), Timestamp('2025-12-18 20:50:00')]

=== FINAL RESULTS ===
Matrix shape: (22, 22, 36)
Matrix dtype: float32

Sample values at time slot 0 (15:00):
[[  0.   43.2 129.  177.  505.8]
 [ 36.    0.   78.  135.  466.8]
 [100.2  63.    0.   67.2 400.8]
 [360.  325.2 270.    0.  337.8]
 [499.8 463.2 402.  378.    0. ]]

Non-zero entries: 16632
Total entries: 17424
Percentage filled: 95.45%

Verification - Travel time from station 0 to station 1 across all time slots:
[43.2 43.2 43.2 43.2 37.2 37.2 37.2 37.2 37.2 37.2 37.2 37.2 37.2 37.2
 37.2 37.8 37.8 37.8 36.  

In [9]:
travel_time_matrix

array([[[  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 43.2,  43.2,  43.2, ...,  36. ,  40.2,  40.2],
        [129. , 129. , 129. , ...,  85.8,  93. ,  93. ],
        ...,
        [189. , 189. , 195. , ..., 157.2, 165. , 165. ],
        [220.2, 220.2, 235.8, ..., 195. , 205.8, 205.8],
        [340.8, 340.8, 349.2, ..., 292.8, 298.8, 298.8]],

       [[ 36. ,  36. ,  36. , ...,  33. ,  31.2,  31.2],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 78. ,  78. ,  78. , ...,  49.2,  52.2,  52.2],
        ...,
        [160.8, 160.8, 171. , ..., 127.2, 133.2, 133.2],
        [196.2, 196.2, 208.8, ..., 159. , 166.2, 166.2],
        [262.8, 262.8, 267. , ..., 259.2, 262.2, 262.2]],

       [[100.2, 100.2, 100.2, ...,  85.2,  79.8,  79.8],
        [ 63. ,  63. ,  63. , ...,  51. ,  49.2,  49.2],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        ...,
        [100.2, 100.2, 100.2, ...,  76.8,  73.2,  73.2],
        [129. , 129. , 130.2, ..., 115.8, 115